image: ubuntu

build:
  stage: build
  before_script:
     - export DEBIAN_FRONTEND=noninteractive
     - apt update && apt -y install make gcc valgrind doxygen graphviz
  script: 
    - /bin/bash test_build.sh
  artifacts:
    paths:
      - bin
      - doc/doxygen
