image: ubuntu16.04

build:
  stage: build
  before_script:
     - export DEBIAN_FRONTEND=noninteractive
     - apt update && apt -y install make gcc valgrind doxygen graphviz
  script: 
    - /bin/bash build_project.sh
  artifacts:
    paths:
      - bin
      - doc/doxygen
test:
    stage: test
    script:
        - /bin/bash Release/test_project.sh
