image: gcc

build:
  stage: build
  before_script: 
    - apt update && apt -y install make 
  script: 
    - gcc helloworld.cpp -o mybinary
  artifacts:
    paths:
      - bin
   cache:
     paths:
       - "*.o"
# run tests using the binary built before
test:
  stage: test
  script:
    - make all
