image: ubuntu

build:
  stage: build
  before_script:
     - export DEBIAN_FRONTEND=noninteractive
     - apt update && apt -y install make gcc valgrind doxygen graphviz
  script: 
    - /bin/bash build_project.sh 1
    - cd Release && make consegna
  artifacts:
    paths:
      - Release
      - doc/doxygen
      - Release/FedericoSilvestri_CorsoA_chatty.tar
test:
    stage: test
    before_script:
        - export DEBIAN_FRONTEND=noninteractive
        - apt update && apt -y install make gcc valgrind doxygen graphviz
        - /bin/bash Release/component_install.sh
    script:
        - cd Release && /bin/bash test_project.sh
        - /bin/bash component_uninstall.sh
